web_assignment_2020/Models/FlightRoute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_assignment_2020.Models
{
    public class FlightRoute
    {
        public int RouteID { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Required, StringLength – cannot exceed 50 characters")]
        public string DepartureCity { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Required, StringLength – cannot exceed 50 characters")]
        public string DepartureCountry { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Required, StringLength – cannot exceed 50 characters")]
        public string ArrivalCity { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Required, StringLength – cannot exceed 50 characters")]
        public string ArrivalCountry { get; set; }

        public int FlightDuration { get; set; }

    }
}

web_assignment_2020/Controllers/FlightRouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using web_assignment_2020.DAL;
using web_assignment_2020.Models;


namespace web_assignment_2020.Controllers
{
    public class FlightRouteController : Controller
    {
        private FlightRouteDAL flightRouteContext = new FlightRouteDAL();


        // GET: FlightRoute
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") == "Admin")
            {
                List<FlightRoute> flightRoutes = flightRouteContext.GetAllFlightRoutes();
                return View(flightRoutes);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: FlightRoute/Details/5
        public ActionResult Details(int id)
        {
            ViewData["routeID"] = id;
            List<FlightScheduleViewModel> flightSchedules = flightRouteContext.GetFlightSchedules(id);
            return View(flightSchedules);
        }

        // GET: FlightRoute/Create
        public ActionResult Create()
        {
            ViewData["minDate"] = DateTime.Today.AddDays(1).ToString();
            return View();
        }

        // POST: FlightRoute/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightRoute flightRoute)
        {
            //Get country list for drop-down list
            //in case of the need to return to Create.cshtml view
            
            if (ModelState.IsValid)
            {
                //Add staff record to database
                flightRoute.RouteID = flightRouteContext.Add(flightRoute);
                //Redirect user to Staff/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(flightRoute);
            }
        }

        // GET: FlightRoute/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FlightRoute/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
    }
}

web_assignment_2020/Views/FlightRoute/Create.cshtml
@model web_assignment_2020.Models.FlightRoute

@{
    ViewData["Title"] = "Create";
}

    <h1>Create Flight Route</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="DepartureCity" class="control-label"></label>
                <input asp-for="DepartureCity" class="form-control" />
                <span asp-validation-for="DepartureCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureCountry" class="control-label"></label>
                <input asp-for="DepartureCountry" class="form-control" />
                <span asp-validation-for="DepartureCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalCity" class="control-label"></label>
                <input asp-for="ArrivalCity" class="form-control" />
                <span asp-validation-for="ArrivalCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalCountry" class="control-label"></label>
                <input asp-for="ArrivalCountry" class="form-control" />
                <span asp-validation-for="ArrivalCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDuration" class="control-label"></label>
                <input asp-for="FlightDuration" class="form-control" min="0"/>
                <span asp-validation-for="FlightDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web_assignment_2020/Views/FlightRoute/Details.cshtml
@model IEnumerable<web_assignment_2020.Models.FlightScheduleViewModel>

<h4 class="PageTitle">Flight Schedules for Route ID: @ViewData["routeID"] </h4>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ScheduleID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FlightNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RouteID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AircraftID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DepartureDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ArrivalDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EconomyClassPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BusinessClassPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ScheduleID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FlightNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RouteID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AircraftID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DepartureDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArrivalDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EconomyClassPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BusinessClassPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>

                </tr>
            }
        </tbody>
    </table>

}
else
{
    <h5 style="text-align: center;font-weight: bold;color: red;margin-top:250px;margin-bottom:250px;" >No flight schedules for selected flight route!</h5>
}

web_assignment_2020/Views/FlightRoute/Index.cshtml
@model IEnumerable<web_assignment_2020.Models.FlightRoute>
@{
    ViewData["Title"] = "View Flight Routes";
}
<h4 class="PageTitle">View Flight Route</h4>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/FlightRoute/_FlightRouteView.cshtml" model="@Model" />

web_assignment_2020/Views/FlightRoute/_FlightRouteView.cshtml
@model IEnumerable<web_assignment_2020.Models.FlightRoute>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RouteID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDuration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RouteID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDuration)
            </td>
            <td>
               
                <a asp-action="Details" asp-controller="FlightRoute"
                   asp-route-id="@item.RouteID">Schedule</a> 
                
            </td>
        </tr>
}
    </tbody>
</table>